@startuml
title ToDoApp_PhisicalModel
/'
## 要件定義
雰囲気で出してみます。
- kintone上で動くシンプルなToDoアプリ
- タスクに対しタスク分類という情報を紐づけられる
- タスク分類の利用方法はユーザにまかせる
- たとえば、プロジェクト毎に分けたり、細かくプロジェクト内の作業内容によって分けたりできる
- タスクに対し優先度情報を紐づけられる
- 優先度情報によってソートが可能
- タスク分類によってデフォルトの優先度が設定できる、設定しないこともできる
- タスクには期日が設定でき、期日順でのソートもできる。
- タスク一覧画面にて、ワンクリックで未完了と完了を切り替えられる


## 基本設計
雰囲気で基本設計をだします。
- A1_タスク一覧、M1_タスク分類、M2_優先度情報がある。
- A1のレコード一覧画面でタスクの完了、未完了を切り替えられる
- チェックボックスで完了未完了切り替え可能
- kintone標準の一覧機能にて完了済みタスク一覧と未完了タスク一覧が見れる
- タスク優先度によって並び替えができる
- タスク追加はレコード追加画面で行う
- M2_優先度情報には必ず優先度名: --- で優先度値: なし の値のデータを入れる
- そのデータは「優先度を設定しない」ことを表すデータとなる

## フィールド一覧
### A1_タスク一覧
- \*タスク名 `タスク一覧で表示する名前`
- タスク詳細 `タスク一覧で表示するタスクの詳細情報`
- \*優先度 `タスク一覧で表示するタスクの優先度情報`
- \*優先度値 `追加画面と詳細画面でのみ表示。優先度フィールドと合わせてM2フィールドから自動挿入される`
- 期日 `タスク一覧で表示するタスクの期日`
- \*タスク分類 `タスク一覧で表示するタスクの分類情報`

### M1_タスク分類
- \*分類名 `A1で表示するタスクの分類名`
- デフォルト優先度 `A1でタスク分類を選択した時に自動的に出力される値`

### M2_優先度情報
- \*優先度名 `A1で表示する優先度を文字として表す値`
- 優先度値 `A1でのソートに使用される値`
'/
entity A1_タスク一覧 as "タスク一覧" {
    *<b>id</b> [PK] [数値]
    ---
    *<b>A1_タスク名</b> [文字列1行]
    <b>A1_タスク詳細</b> [文字列複数行]
    *<b>A1_優先度</b> [ルックアップ: M2_優先度名]
    *<b>A1_優先度値</b> [数値]
    <b>A1_期日</b> [日付]
    *<b>A1_タスク分類</b> [ルックアップ: M1_タスク分類名]
}

entity M1_タスク分類 as "タスク分類" {
    *<b>id</b> [PK] [数値]
    ---
    *<b>M1_分類名</b> [文字列1行]
    <b>M1_デフォルト優先度</b> [ルックアップ: M2_優先度名]
}

entity M2_優先度情報 as "優先度情報" {
    *<b>id</b> [PK] [数値]
    ---
    *<b>M2_優先度名</b> [文字列1行]
    <b>M2_優先度値</b> [数値]
}

A1_タスク一覧 }o--|| M1_タスク分類
A1_タスク一覧 }o--|| M2_優先度情報
M1_タスク分類 }o--|| M2_優先度情報

@enduml